#!/usr/bin/env bash
# L1 Wrapper API: query_hotline_workorders
# Mock: 查询 2911 热线产生的工单详情
# Usage: query_hotline_workorders.sh [--date YYYY-MM-DD] [--level L1|L2|L3|L4] [--status pending|in_progress|resolved|closed]

set -euo pipefail

DATE="$(date +%Y-%m-%d)"
LEVEL=""
STATUS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --date)   DATE="$2";   shift 2 ;;
    --level)  LEVEL="$2";  shift 2 ;;
    --status) STATUS="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# Base work orders data
cat <<JSON
{
  "success": true,
  "hotline": "2911",
  "date": "$DATE",
  "summary": {
    "totalWorkOrders": 23,
    "byLevel": {
      "L1": { "count": 3, "label": "紧急", "pct": 0.130 },
      "L2": { "count": 5, "label": "高",   "pct": 0.217 },
      "L3": { "count": 10, "label": "中",  "pct": 0.435 },
      "L4": { "count": 5, "label": "低",   "pct": 0.217 }
    },
    "byStatus": {
      "pending":     { "count": 4, "label": "待处理" },
      "in_progress": { "count": 8, "label": "处理中" },
      "resolved":    { "count": 9, "label": "已解决" },
      "closed":      { "count": 2, "label": "已关闭" }
    },
    "overdueCount": 2,
    "avgResolutionTimeMinutes": 85
  },
  "workOrders": [
    {
      "woId": "WO-20260712-001",
      "level": "L1",
      "title": "IDC-A区核心交换机 down — BGP 邻居全部丢失",
      "category": "网络设备故障",
      "source": "2911热线",
      "callerName": "李建国",
      "callerDept": "IDC 运维部",
      "callTime": "2026-07-12T08:23:15",
      "status": "in_progress",
      "assignedTo": "张羽辰",
      "assignedTeam": "网络运维组",
      "slaDeadline": "2026-07-12T08:53:15",
      "resolutionTimeMinutes": null,
      "isOverdue": false,
      "notes": "已初步定位为光模块故障，正在更换 QSFP28 100G SR4"
    },
    {
      "woId": "WO-20260712-002",
      "level": "L1",
      "title": "总部大楼全楼层断网 — 核心路由器重启",
      "category": "网络设备故障",
      "source": "2911热线",
      "callerName": "王芳",
      "callerDept": "行政部",
      "callTime": "2026-07-12T10:15:30",
      "status": "in_progress",
      "assignedTo": "陈工",
      "assignedTeam": "网络运维组",
      "slaDeadline": "2026-07-12T10:45:30",
      "resolutionTimeMinutes": null,
      "isOverdue": true,
      "notes": "RTR-001 异常重启，正在排查电源模块"
    },
    {
      "woId": "WO-20260712-003",
      "level": "L1",
      "title": "DCI 专线中断 — 上海→深圳丢包率 80%",
      "category": "线路故障",
      "source": "2911热线",
      "callerName": "赵磊",
      "callerDept": "云平台运维",
      "callTime": "2026-07-12T10:08:00",
      "status": "pending",
      "assignedTo": "未分配",
      "assignedTeam": "网络运维组",
      "slaDeadline": "2026-07-12T10:38:00",
      "resolutionTimeMinutes": null,
      "isOverdue": true,
      "notes": "已通知运营商排查，待回电"
    },
    {
      "woId": "WO-20260712-004",
      "level": "L2",
      "title": "VPN 网关负载过高 — 高峰时段连接超时",
      "category": "系统性能",
      "source": "2911热线",
      "callerName": "刘洋",
      "callerDept": "安全运维",
      "callTime": "2026-07-12T09:45:00",
      "status": "in_progress",
      "assignedTo": "周工",
      "assignedTeam": "网络安全组",
      "slaDeadline": "2026-07-12T11:45:00",
      "resolutionTimeMinutes": null,
      "isOverdue": false,
      "notes": "正在扩容 VPN 网关实例"
    },
    {
      "woId": "WO-20260712-005",
      "level": "L2",
      "title": "财务系统访问异常 — 数据库连接池耗尽",
      "category": "应用系统故障",
      "source": "2911热线",
      "callerName": "孙丽",
      "callerDept": "财务部",
      "callTime": "2026-07-12T10:30:00",
      "status": "resolved",
      "assignedTo": "吴工",
      "assignedTeam": "应用运维组",
      "slaDeadline": "2026-07-12T12:30:00",
      "resolutionTimeMinutes": 45,
      "isOverdue": false,
      "notes": "重启应用服务后恢复，已增加连接池上限"
    },
    {
      "woId": "WO-20260712-006",
      "level": "L2",
      "title": "WiFi 控制器 HA 切换失败 — 手动恢复",
      "category": "网络设备故障",
      "source": "2911热线",
      "callerName": "赵工",
      "callerDept": "IT 支持",
      "callTime": "2026-07-12T08:50:00",
      "status": "resolved",
      "assignedTo": "张羽辰",
      "assignedTeam": "网络运维组",
      "slaDeadline": "2026-07-12T10:50:00",
      "resolutionTimeMinutes": 55,
      "isOverdue": false,
      "notes": "WLC-002 手动接管，原 master 需 RMA"
    },
    {
      "woId": "WO-20260712-007",
      "level": "L2",
      "title": "邮件系统延迟严重 — 外发队列堆积 >500",
      "category": "应用系统故障",
      "source": "2911热线",
      "callerName": "马超",
      "callerDept": "市场部",
      "callTime": "2026-07-12T11:00:00",
      "status": "in_progress",
      "assignedTo": "黄工",
      "assignedTeam": "应用运维组",
      "slaDeadline": "2026-07-12T13:00:00",
      "resolutionTimeMinutes": null,
      "isOverdue": false,
      "notes": "垃圾邮件攻击导致队列堆积，正在清洗"
    },
    {
      "woId": "WO-20260712-008",
      "level": "L2",
      "title": "客服系统页面加载缓慢 — CDN 节点异常",
      "category": "系统性能",
      "source": "2911热线",
      "callerName": "林工",
      "callerDept": "客服部",
      "callTime": "2026-07-12T11:20:00",
      "status": "in_progress",
      "assignedTo": "周工",
      "assignedTeam": "应用运维组",
      "slaDeadline": "2026-07-12T13:20:00",
      "resolutionTimeMinutes": null,
      "isOverdue": false,
      "notes": "已切换到备用 CDN 节点，正在回源"
    },
    {
      "woId": "WO-20260712-009",
      "level": "L3",
      "title": "会议室投屏设备无法连接",
      "category": "终端设备",
      "source": "2911热线",
      "callerName": "张明",
      "callerDept": "行政部",
      "callTime": "2026-07-12T08:10:00",
      "status": "resolved",
      "assignedTo": "陈工",
      "assignedTeam": "IT 支持",
      "slaDeadline": "2026-07-12T12:10:00",
      "resolutionTimeMinutes": 30,
      "isOverdue": false,
      "notes": "HDMI 线缆故障，已更换"
    },
    {
      "woId": "WO-20260712-010",
      "level": "L3",
      "title": "新员工电脑无法加域",
      "category": "账号权限",
      "source": "2911热线",
      "callerName": "李工",
      "callerDept": "HR",
      "callTime": "2026-07-12T08:30:00",
      "status": "resolved",
      "assignedTo": "陈工",
      "assignedTeam": "IT 支持",
      "slaDeadline": "2026-07-12T12:30:00",
      "resolutionTimeMinutes": 40,
      "isOverdue": false,
      "notes": "AD 账号未同步，已手动添加"
    },
    {
      "woId": "WO-20260712-011",
      "level": "L3",
      "title": "SAP 系统打印凭证乱码",
      "category": "应用系统",
      "source": "2911热线",
      "callerName": "孙丽",
      "callerDept": "财务部",
      "callTime": "2026-07-12T09:00:00",
      "status": "resolved",
      "assignedTo": "吴工",
      "assignedTeam": "应用运维组",
      "slaDeadline": "2026-07-12T13:00:00",
      "resolutionTimeMinutes": 60,
      "isOverdue": false,
      "notes": "打印机驱动配置问题，已修复"
    },
    {
      "woId": "WO-20260712-012",
      "level": "L3",
      "title": "共享文件夹权限丢失 — 部门无法访问",
      "category": "账号权限",
      "source": "2911热线",
      "callerName": "赵磊",
      "callerDept": "云平台运维",
      "callTime": "2026-07-12T09:15:00",
      "status": "resolved",
      "assignedTo": "陈工",
      "assignedTeam": "IT 支持",
      "slaDeadline": "2026-07-12T13:15:00",
      "resolutionTimeMinutes": 35,
      "isOverdue": false,
      "notes": "权限组误操作被清空，已从备份恢复"
    },
    {
      "woId": "WO-20260712-013",
      "level": "L3",
      "title": "监控大屏数据不刷新",
      "category": "应用系统",
      "source": "2911热线",
      "callerName": "刘洋",
      "callerDept": "安全运维",
      "callTime": "2026-07-12T09:30:00",
      "status": "resolved",
      "assignedTo": "黄工",
      "assignedTeam": "应用运维组",
      "slaDeadline": "2026-07-12T13:30:00",
      "resolutionTimeMinutes": 50,
      "isOverdue": false,
      "notes": "WebSocket 连接断开，重启前端服务恢复"
    },
    {
      "woId": "WO-20260712-014",
      "level": "L3",
      "title": "电话分机 305 无拨号音",
      "category": "终端设备",
      "source": "2911热线",
      "callerName": "王芳",
      "callerDept": "行政部",
      "callTime": "2026-07-12T10:00:00",
      "status": "pending",
      "assignedTo": "未分配",
      "assignedTeam": "IT 支持",
      "slaDeadline": "2026-07-12T14:00:00",
      "resolutionTimeMinutes": null,
      "isOverdue": false,
      "notes": ""
    },
    {
      "woId": "WO-20260712-015",
      "level": "L3",
      "title": "门禁系统刷卡无响应 — 3号门",
      "category": "终端设备",
      "source": "2911热线",
      "callerName": "张明",
      "callerDept": "行政部",
      "callTime": "2026-07-12T10:15:00",
      "status": "in_progress",
      "assignedTo": "陈工",
      "assignedTeam": "IT 支持",
      "slaDeadline": "2026-07-12T14:15:00",
      "resolutionTimeMinutes": null,
      "isOverdue": false,
      "notes": "读卡器故障，正在更换"
    },
    {
      "woId": "WO-20260712-016",
      "level": "L3",
      "title": "企业微信消息延迟 15 分钟",
      "category": "应用系统",
      "source": "2911热线",
      "callerName": "马超",
      "callerDept": "市场部",
      "callTime": "2026-07-12T11:30:00",
      "status": "pending",
      "assignedTo": "未分配",
      "assignedTeam": "应用运维组",
      "slaDeadline": "2026-07-12T15:30:00",
      "resolutionTimeMinutes": null,
      "isOverdue": false,
      "notes": ""
    },
    {
      "woId": "WO-20260712-017",
      "level": "L3",
      "title": "机房空调温度偏高报警",
      "category": "基础设施",
      "source": "2911热线",
      "callerName": "李建国",
      "callerDept": "IDC 运维部",
      "callTime": "2026-07-12T13:00:00",
      "status": "resolved",
      "assignedTo": "赵工",
      "assignedTeam": "基础设施组",
      "slaDeadline": "2026-07-12T17:00:00",
      "resolutionTimeMinutes": 90,
      "isOverdue": false,
      "notes": "过滤网堵塞，已清洗。温度恢复正常"
    },
    {
      "woId": "WO-20260712-018",
      "level": "L3",
      "title": "视频会议系统回声严重",
      "category": "终端设备",
      "source": "2911热线",
      "callerName": "孙丽",
      "callerDept": "财务部",
      "callTime": "2026-07-12T14:00:00",
      "status": "in_progress",
      "assignedTo": "陈工",
      "assignedTeam": "IT 支持",
      "slaDeadline": "2026-07-12T18:00:00",
      "resolutionTimeMinutes": null,
      "isOverdue": false,
      "notes": "已远程调试音频参数，待用户确认"
    },
    {
      "woId": "WO-20260712-019",
      "level": "L4",
      "title": "申请安装 Photoshop — 设计师新入职",
      "category": "软件安装",
      "source": "2911热线",
      "callerName": "马超",
      "callerDept": "市场部",
      "callTime": "2026-07-12T08:45:00",
      "status": "in_progress",
      "assignedTo": "陈工",
      "assignedTeam": "IT 支持",
      "slaDeadline": "2026-07-13T08:45:00",
      "resolutionTimeMinutes": null,
      "isOverdue": false,
      "notes": "等待 license 审批"
    },
    {
      "woId": "WO-20260712-020",
      "level": "L4",
      "title": "更换工位网络面板 — B栋3楼A区",
      "category": "终端设备",
      "source": "2911热线",
      "callerName": "王芳",
      "callerDept": "行政部",
      "callTime": "2026-07-12T09:00:00",
      "status": "closed",
      "assignedTo": "陈工",
      "assignedTeam": "IT 支持",
      "slaDeadline": "2026-07-13T09:00:00",
      "resolutionTimeMinutes": 120,
      "isOverdue": false,
      "notes": "面板已更换，端口已激活"
    },
    {
      "woId": "WO-20260712-021",
      "level": "L4",
      "title": "数据备份策略咨询",
      "category": "咨询",
      "source": "2911热线",
      "callerName": "刘洋",
      "callerDept": "安全运维",
      "callTime": "2026-07-12T10:00:00",
      "status": "resolved",
      "assignedTo": "周工",
      "assignedTeam": "网络安全组",
      "slaDeadline": "2026-07-13T10:00:00",
      "resolutionTimeMinutes": 25,
      "isOverdue": false,
      "notes": "已提供备份策略文档链接"
    },
    {
      "woId": "WO-20260712-022",
      "level": "L4",
      "title": "申请访客 WiFi 临时账号 — 供应商3人",
      "category": "账号权限",
      "source": "2911热线",
      "callerName": "赵磊",
      "callerDept": "云平台运维",
      "callTime": "2026-07-12T11:00:00",
      "status": "closed",
      "assignedTo": "陈工",
      "assignedTeam": "IT 支持",
      "slaDeadline": "2026-07-13T11:00:00",
      "resolutionTimeMinutes": 15,
      "isOverdue": false,
      "notes": "已创建临时账号，有效期3天"
    },
    {
      "woId": "WO-20260712-023",
      "level": "L4",
      "title": "IT 资产领用 — 无线鼠标 x2",
      "category": "资产管理",
      "source": "2911热线",
      "callerName": "张明",
      "callerDept": "行政部",
      "callTime": "2026-07-12T13:30:00",
      "status": "pending",
      "assignedTo": "未分配",
      "assignedTeam": "IT 支持",
      "slaDeadline": "2026-07-13T13:30:00",
      "resolutionTimeMinutes": null,
      "isOverdue": false,
      "notes": ""
    }
  ]
}
JSON
